import type { Metadata } from "next";
import "./globals.css";
import { Analytics } from "@vercel/analytics/react";
import Nav from "@/components/nav";
import Logo from "@/components/logo";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<div className="flex flex-row sticky top-0 bg-[#ffffff] z-10">
					<Logo />
					<Nav />
				</div>
				{children}
				<Analytics />
			</body>
		</html>
	);
}
