import type { Metadata } from "next";
import "./globals.css";
import { Analytics } from "@vercel/analytics/react";
import Nav from "@/components/nav";
import Footer from "@/components/footer";
import { GoogleOAuthProvider } from "@react-oauth/google";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<Nav />
				{children}
				<Footer />
				<Analytics />
			</body>
		</html>
	);
}
